name: Code Quality Check
on:
  pull_request:
    types: [opened]

jobs:
  prettier:
    runs-on: ubuntu-latest
    if: github.base_ref != 'refs/heads/release/*'


    steps:
      - name: Prettierfy and commit
        run: |
         echo "Prettierfy and commit"
         echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "github.base_ref: ${{  github.base_ref }}"

  eslint:
    if: github.base_ref == 'nextjs' || github.base_ref == 'nextjs-prod' ||  github.base_ref == 'release/*'
    needs: prettier
    runs-on: ubuntu-latest

    steps:
      - name: ESLINTING
        run: |
         echo "ESLINTING HERE"
         echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "github.base_ref: ${{  github.base_ref }}"
