name: Code Quality Check
on:
  pull_request:
   types: [opened, synchronize]

jobs:
  prettier:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && !startsWith(github.base_ref, 'release/')
    steps:
      - name: Prettierfy and commit
        run: |
         echo "Prettierfy and commit"
         echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "github.base_ref: ${{  github.base_ref }}"

  eslint:
   
    needs: prettier
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.base_ref == 'nextjs' || github.base_ref == 'nextjs-prod' ||  startsWith(github.base_ref, 'release/')
    steps:
      - name: ESLINTING
        run: |
         echo "ESLINTING HERE"
         echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "github.base_ref: ${{  github.base_ref }}"
