#This workflow checks the formatting of code files using Prettier and automatically commits any changes that need to be made to the code formatting.

name: Run prettier

on:
  pull_request:
    types:
      - opened
    branches:
      - nextjs
      - "!release/**"

jobs:
  prettier-check-and-commit:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
      - name: Save Branch Name to GitHub Environment Variable
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn install
      - name: Check Prettier Formatting
        id: prettier-check
        run: |
          npx prettier --check "{src,project_utils,puppeteer,tests}/**/*.{js,ts,tsx,json}" "*.{js,ts,json}" "../.github/**/*.yml" --ignore-path="{../yarn.lock,../package.json}"
        continue-on-error: true
      - name: Auto-format Code and Commit Prettier Changes
        if: steps.prettier-check.outcome == 'failure'
        run: |
          git fetch --unshallow
          git checkout ${{ env.BRANCH_NAME }}
          npx prettier --write "{src,project_utils,puppeteer,tests}/**/*.{js,ts,tsx,json}" "*.{js,ts,json}" "../.github/**/*.yml" --ignore-path="{../yarn.lock,../package.json}"
          git config --global user.email "commit-bot@example.com"
          git config --global user.name "Commit Bot"
          git add -A
          git commit -m "chore: Auto-run Prettier on files in PR" --no-verify
          git push origin ${{ env.BRANCH_NAME }}
